import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/layout/Header/Header'
import { Footer } from '@/components/layout/Footer/Footer'
const robotoFont = Roboto({
	variable: '--font-roboto',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Eventify',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className={`${robotoFont.variable} h-full antialiased`}
		>
			<body className='flex flex-col min-h-full'>
				<Header />
				<div className='min-h-screen bg-gray-50'>{children}</div>
				<Footer />
			</body>
		</html>
	)
}
