FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY EventApp/EventApp.csproj EventApp/
RUN dotnet restore EventApp/EventApp.csproj

COPY EventApp/. EventApp/
WORKDIR /src/EventApp
RUN dotnet publish EventApp.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "EventApp.dll"]
